[settings]
prefixes = ["!", "?", ";", "~", ".", ","]
desc = "A small moderation and management bot for the RFMP comp server"
creator_id = 223903236069785601

[team]
blue_role_id = 599350029324386318
red_role_id = 599350068272693278
